### ISSUE TITLE
Desktop file/Metainfo changes

### ISSUE THREAD

**Issue by hellcp** [yast/yast-yast2#934]
- [x] yast/yast-add-on#77
- [x] yast/yast-alternatives#44
- [x] yast/yast-apparmor#39
- [x] yast/yast-audit-laf#21
- [x] yast/yast-auth-client#74
- [x] yast/yast-auth-server#51
- [x] yast/yast-autoinstallation#509
- [x] yast/yast-bootloader#570
- [x] yast/yast-boot-server#14
- [x] yast/yast-cio#31
- [x] yast/yast-cluster#51
- [x] yast/yast-configuration-management#71
- [x] yast/yast-country#216
- [x] yast/yast-crowbar#65
- [x] yast/yast-dhcp-server#44
- [x] yast/yast-dns-server#80
- [x] yast/yast-docker#27
- [x] yast/yast-drbd#22
- [x] yast/yast-fcoe-client#56
- [x] yast/yast-firewall#125
- [x] yast/yast-fonts#43
- [x] yast/yast-ftp-server#56
- [x] yast/yast-geo-cluster#26
- [x] yast/yast-http-server#43
- [x] yast/yast-instserver#41
- [x] yast/yast-iplb#17
- [x] yast/yast-iscsi-client#85
- [x] yast/yast-iscsi-lio-server#95
- [x] yast/yast-isns#24
- [x] yast/yast-journal#42
- [x] yast/yast-kdump#105
- [x] yast/yast-mail#42
- [x] yast/yast-migration#49
- [x] yast/yast-multipath#29
- [x] yast/yast-nfs-client#82
- [x] yast/yast-nfs-server#33
- [x] yast/yast-nis-client#42
- [x] yast/yast-nis-server#18
- [x] yast/yast-ntp-client#136
- [x] yast/yast-online-update#28
- [x] yast/yast-online-update-configuration#22
- [x] yast/yast-printer#27
- [x] yast/yast-proxy#25
- [x] yast/yast-rdp#19
- [x] yast/yast-rear#17
- [x] yast/yast-registration#436
- [x] yast/yast-reipl#24
- [x] yast/yast-samba-client#77
- [x] yast/yast-samba-provision#3
- [x] yast/yast-samba-server#67
- [x] yast/yast-scanner#23
- [x] yast/yast-security#51
- [x] yast/yast-services-manager#192
- [x] yast/yast-slp-server#30
- [x] yast/yast-snapper#69
- [x] yast/yast-sound#33
- [x] yast/yast-squid#27
- [x] yast/yast-storage-ng#927
- [x] yast/yast-sudo#10
- [x] yast/yast-support#36
- [x] yast/yast-sysconfig#27
- [x] yast/yast-tftp-server#29
- [x] yast/yast-tune#38
- [x] yast/yast-update#127
- [x] yast/yast-users#208
- [x] yast/yast-vm#42
- [x] yast/yast-vpn#11
- [x] yast/yast-yast2#933
- [x] yast/yast-control-center#42
- [x] yast/yast-packager#446
- [x] yast/yast-devtools#142
- [x] yast/yast-packager#448

**Comment by shundhammer** [comment]
All reviewed and merged.

**Comment by hellcp** [comment]
- [ ] https://github.com/yast/yast-migration/pull/49/
- [ ] https://github.com/yast/yast-network/pull/828
- [ ] https://github.com/yast/yast-firstboot/pull/72
- [ ] https://github.com/yast/yast2-adsi/pull/5
- [ ] https://github.com/yast/yast-s390/pull/68
- [ ] https://github.com/yast/yast2-gpmc/pull/7
- [ ] https://github.com/yast/yast-installation/pull/800
- [ ] https://github.com/yast/yast2-aduc/pull/3

**Comment by lslezak** [comment]
All reviewed and merged! @hellcp, thanks a lot ! :+1: :medal_sports:
